# Generated by Django 3.2.16 on 2024-08-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktest2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Shop',
        ),
    ]
